[package]
name = "data-classes"
version = "0.0.0-3"
edition = "2024"
authors = ["copi143 <copi143@outlook.com>"]
license = "MIT OR Apache-2.0"
description = "Abbreviation of #[derive(xxx)]"
homepage = "https://github.com/copi143/data-classes"
repository = "https://github.com/copi143/data-classes"
readme = "README.md"

[features]
default = ["full"]
full = ["rkyv", "serde", "bytemuck"]
rkyv = ["data-classes-derive/rkyv", "dep:rkyv"]
serde = ["data-classes-derive/serde", "dep:serde"]
bytemuck = ["data-classes-derive/bytemuck", "dep:bytemuck"]

[dependencies]
data-classes-derive = { version = "=0.0.0-3", path = "../derive" }
rkyv = { version = "0.8.12", optional = true }
serde = { version = "1.0.228", features = ["derive"], optional = true }
bytemuck = { version = "1.24.0", optional = true }
